### PR TITLE
Geospatial Caching PR Fixes

### PR DESCRIPTION
**Pull request by jacob6838**
This PR fixes comments made within the Geospatial Caching pr: https://github.com/CDOT-CV/Work_Zone/pull/49. These changes include:
- removing icone_arrow_board scripts - these were not generalized enough to be included in the public repo
- Removing private keys from monitoring scripts
- Adding additional documentation and comments

### CODE REVIEW

**Comment by jacob6838** [comment]
@payneBrandon @drewjj This PR fixes all of the issues addressed in https://github.com/CDOT-CV/Work_Zone/pull/49!

**Comment by jacob6838** [comment]
The deprecation warnings resolutions (ignoring both) are archived in this work item: https://dev.azure.com/SOC-OIT/CDOT/_sprints/backlog/CDOT%20Connected%20Vehicles/CDOT/CDOT%20Connected%20Vehicles/CV%20Sprint%2065?workitem=222607

**Comment by jacob6838** [comment]
There are a few changes to the identify_overlapping_features methods in this PR (3 separate methods in 3 separate files), which help to optimize the experimental feed processing, which will not show up in the comments on PR 49

**Review by drewjj — APPROVED** [review]
Looks good!

**Pull request merged**
